# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CatAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatAPI
  pod 'Alamofire'
  pod "PromiseKit", "~> 6.8"
  pod 'Logging'
  pod 'SwiftyJSON'

  target 'CatAPITests' do
    inherit! :search_paths
    # Pods for testing
    pod "PromiseKit", "~> 6.8" 
  end

end
